### ISSUE TITLE
Unable to send json in POST request

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#100]
I have set header as

```
Content-Type: application/json
```

and added json in the post body

![image](https://user-images.githubusercontent.com/1576632/65833931-602cf480-e2f3-11e9-9289-5151d1a039e2.png)

**Comment by d3ep4k** [comment]
Also if there is a unit test, please update it so it helps to cover this case

**Comment by ancode4** [comment]
Hello @d3ep4k, your json syntax is invalid. The json keys should be inside quotes:

```javascript
{
    "value" : {
        "name" : "Deepak"
    }
}
```

**Comment by d3ep4k** [comment]
You are right. 

```xml
<Resource xmlns="http://xml.metamug.net/resource/1.0" v="1.0">
	<Request method="POST">
		<Output id="requestContent" value="$value.name" />
	</Request>
</Resource>
```
