### ISSUE TITLE
Convert JSON Payload to POJO

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#106]
Instead of using JSON path, EL can be used if the json had been converted to POJO. This will help improve performance of the request handling.

**Comment by d3ep4k** [comment]
@richard937 does this work with jackson ?

**Comment by richard937** [comment]
yes json works fine for both simple and complex type
![bulkpostjson](https://user-images.githubusercontent.com/42942897/86535336-3a292600-befd-11ea-9175-5e91253c7260.PNG)
![post](https://user-images.githubusercontent.com/42942897/86535338-3e554380-befd-11ea-9d2e-3e29a5ff6d93.PNG)
