### ISSUE TITLE
Reusing sql written in another resource 

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#11]
Currently mason doesn’t allow a mechanism to reuse queries. I have to rewrite same queries multiple times in different resources and may be in same resource for different methods.

**Comment by ancode4** [comment]
Queries can now be stored in a props file and referenced inside the jsp
https://github.com/metamug/mason/commit/39888e163ce90bfbf06045ef04088742216944d1

**Comment by d3ep4k** [comment]
So now same query can be referenced by multiple jsps.

**Comment by ancode4** [comment]
Yes. Multiple jsps in the same webapp can reuse queries. The props file gets loaded on deployment of the webapp, so updating the props file will not immediately reflect in the API. The app will need to be re-deployed or the server restarted.
