### ISSUE TITLE
route to resource without parent id

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#113]
```
/crm/323/customer/320
```

In the above case, we may NOT have multiple CRM so the request should be routed to the JSP as follows

```
/crm/customer/320
```

**Comment by ancode4** [comment]
Updated request adapter to allow route without parent ID.
https://github.com/metamug/mason/commit/b586a26949b758d1fc25f1d3afca45569a81baf0

So now, when a request is made without parent ID. Eg. `/crm/customer/320` , then the router should route to the resource `customer`. Note that, here the parent `crm` should be non-existent. This will indicate that `crm` is just a group for the resource.

**Comment by richard937** [comment]
when I tried to send e get request to entertainment/movie I am getting a blank page. I am using mason-microservice with mason version 3.4

![err](https://user-images.githubusercontent.com/42942897/80592023-58c1fb00-8a3c-11ea-8f29-c00929d8eeac.PNG)

and for entertainment/movie/1 getting 404 error

![er1](https://user-images.githubusercontent.com/42942897/80592043-637c9000-8a3c-11ea-9f0d-1c3b773146e3.PNG)

**Comment by ancode4** [comment]
Ok. Do both of your resource jsp files (entertainment & movie) exist?

**Comment by richard937** [comment]
yes both are present. I can send a get request from movie/id

![err](https://user-images.githubusercontent.com/42942897/80614576-3fc94200-8a5c-11ea-88b8-77575b7f6f3f.PNG)

![erre](https://user-images.githubusercontent.com/42942897/80614590-42c43280-8a5c-11ea-831b-440b4be7a2d9.PNG)

**Comment by d3ep4k** [comment]
Isn't it related to this issue? Are we able to create parent tag ? Is the following working?

```
/entertainment/12/movie
```
Once this works

we will try making
```
/entertainment/movie
```
work

**Comment by d3ep4k** [comment]
Trying the following treats it like its child. which is valid.

```cmd
http://localhost:7000/rest/v1.0/entertainment/movie/
```

**Comment by d3ep4k** [comment]
Can this issue take care of #41 to improve efficiency

**Comment by d3ep4k** [comment]
Need to test with 

```jsp
<m:resource parentName="crm">
</m:resource>
```
