### ISSUE TITLE
Accessing request body

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#120]
I'm sending my POST request as xml body. How do I access this xml body to be used by sql and execute tags further.

There is a json strategy to access the request, where we can access the raw json. But need something similar for xml strategy.

https://github.com/metamug/mason/blob/master/src/main/java/com/metamug/mason/entity/request/JsonStrategy.java

**Comment by ancode4** [comment]
https://github.com/metamug/mason/issues/121

**Comment by richard937** [comment]
POST request made by xml body 
![xmlpostreq](https://user-images.githubusercontent.com/42942897/84178609-507cc700-aaa2-11ea-9f24-9fe7c7ae5bcd.PNG)
