### ISSUE TITLE
Need request model for JSON/XML request body 

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#121]
Request tag can have `model` attribute which will take class name of a model class
`com.example.model.Customer`

The XML request body can be parsed to create the model object.
This can be done in the `doStartTag` method of com.metamug.mason.tag.RequestTagHandler.java

If the incoming XML cannot be parsed, return status code 422.
If model class cannot be found, return 512.

**Comment by richard937** [comment]
post request made with XML body is failing

![Capture](https://user-images.githubusercontent.com/42942897/83936652-32ce0a00-a7e3-11ea-94e4-27c316d2d13e.PNG)
