### ISSUE TITLE
Identifying the item request identifier

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#129]
The current request jsp tag requests item attribute to be a boolean type.

```jsp
<m:request method="POST"  item="true">
    <%-- child tags--%>
<m:request>
```

We can change the item attribute value to a given item name. And add a variable that can used
to access the element from the pathname.

```jsp
<m:request method="POST"  item="itemname">
    <%-- child tags--%>
<m:request>
```

**Comment by d3ep4k** [comment]
@richard937 please check this and close as well.

**Comment by richard937** [comment]
> @richard937 please check this and close as well.

Yes item attribute has been converted to string from boolean
