### ISSUE TITLE
Put mason on maven central

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#13]
I cannot include mason as dependency in my maven project. Can someone please put this on maven central repo.

**Comment by d3ep4k** [comment]
if put on maven central, javadocs.io could display javadocs.

**Comment by kaisteel** [comment]
Mason is now available on mason
```
<dependency>
  <groupId>com.metamug</groupId>
  <artifactId>mason</artifactId>
  <version>3.2</version>
</dependency>
```
