### ISSUE TITLE
json request to object without class

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#131]
Convert json data into Java Object that supports Map. This enables it to be used in jsp

https://github.com/fangyidong/json-simple

**Comment by d3ep4k** [comment]
@richard937 can you please verify and close this issue. This has been worked upon in request tag.

**Comment by richard937** [comment]
I used this POST request to check if it is working without the className
![postwithoutclass](https://user-images.githubusercontent.com/42942897/86536293-056c9d00-bf04-11ea-921b-802422dda69d.PNG)
and it worked
![post](https://user-images.githubusercontent.com/42942897/86536316-38af2c00-bf04-11ea-8d19-8f1c38558ec0.PNG)
![succes](https://user-images.githubusercontent.com/42942897/86536320-406ed080-bf04-11ea-8438-8ceba0acb1c6.PNG)
