### ISSUE TITLE
Taglib documentation

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#135]
Provide documentation for all the jsp tags for rest api.

**Comment by d3ep4k** [comment]
@kaisteel if you can generate the documentation. I can publish it on github docs.

**Comment by kaisteel** [comment]
The docs can be generated with the Tagdoc lib.. but you need to put some description about the tags in .tld file. Currently everything is getting generated as HTML with empty tables.

**Comment by d3ep4k** [comment]
https://github.com/metamug/mason/tree/taglib_doc
on this branch
please check and merge
and generate documentation
with master
took this branch from master
