### ISSUE TITLE
Get 512 while triggering UploadEvent during file Upload

### ISSUE THREAD

**Issue by kaisteel** [metamug/mason#14]
**Describe the bug**
I tried using the UploadEvent feature to process file that I've uploaded. But every time I hit API to upload the file it returns 512. Described below steps to reproduce the error.

**To Reproduce**
1. Create a backend.
2. Upload a maven project containing a class that implements _UploadListener_ interface
3. Create a Resource file containing a POST request.
4. Try uploading a file on the resource created at Step 3.

Here is the error message I get:
![error_message](https://user-images.githubusercontent.com/8086855/49331531-7af3e700-f5c4-11e8-8f19-d93d951b9007.PNG)

**System Info:**
 - OS: Win-8.1x64
 - Metamug Version: 0.6.1

**Comment by d3ep4k** [comment]
Does this work now. Has anyone started developing this ?

**Comment by kaisteel** [comment]
This (8d68965bbead782ba107d2b9035c6c6ff47dde5c) fixes the issue, loading of `config.properties` file had appBase path dependency since it was hard-coded. The `config` file is now being loaded via `classLoader()` which solves the problem.
