### ISSUE TITLE
Unable to use jsonPath on xrequest result

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#156]
```
<m:request method="GET">

    <c:set var="Issue-ID" scope="page" value="${mtgReq.params['issueId']}"/>
    <c:set target="${output}" property="Issue-ID" value="${pageScope['Issue-ID']}"/>

    <m:xrequest var="issue" method="GET" output="true" url="https://metamug.atlassian.net/rest/api/3/issue/CON-127">
      <m:header name="Authorization" value="Basic YW5pc2guaGlybGVrYXJAbWV0YW11Zy5jb206dW5pMk1TcWNLYnpIVk4xOVJsVng1ODNF"/>
    </m:xrequest>


    <c:set var="issueSummary" scope="page" value="${m:jsonPath('$.key',issue)}"/>
    <c:set target="${output}" property="issueSummary" value="${pageScope['issueSummary']}"/>
  </m:request>
```

Get this error
```
{"message":"/WEB-INF/resources/v1.0/jira.jsp (line: [15], column: [4]) The function [jsonPath] cannot be located with the specified prefix","status":500}
```

**Comment by d3ep4k** [comment]
jsonPath function has been removed in mason 4.  Use JSP expression language to achieve the behaviour. 

Kindly go through the below examples. If required we can add more examples to demonstrate jsonPath replacement.

https://github.com/metamug/mason/blob/develop/server/src/main/webapp/WEB-INF/resources/v1.0/jwt/token.jsp
https://github.com/metamug/mason/blob/develop/server/src/main/webapp/WEB-INF/resources/v1.0/payload/movie.jsp

**Comment by ancode4** [comment]
EL does not work for xrequest object as it returns org.json.JSONObject.

So in my example, using `${issue.key}` throws the following

```
'${issue.key}' Property [key] not found on type [org.json.JSONObject]
```

**Comment by d3ep4k** [comment]
In such a case we need to return Simple  json object, the strategy used to handle incoming json request payload. We have used Json-simple library. It works directly from with EL unlike org.json. Check #131 for implementation. 

The change needs to be made in xrequest tag class. Take a separate branch And commit changes and submit PR into dev

Also take a look at #117, since that is xrequest related.

**Comment by ancode4** [comment]
https://github.com/metamug/mason/commit/e699978e9e4629625d334374454f3668f7e6ffa1

Converted org.json objects to org.json.simple objects in addToBus() so they can be resolved using EL.
But putting org.json objects as they are in the output map because JAXB can only read and convert org.json objects into json string and not so with org.json.simple.
