### ISSUE TITLE
Implement JWT Auth

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#3]
Implement JWT authentication with queries. https://metamug.com/docs/auth.php#token-based-auth

**Comment by d3ep4k** [comment]
So jwt goes in group tag handler. Have added the verification code there. Since jwt verification is done using custom tag.  Generating the jwt token part is pending.

**Comment by ancode4** [comment]
Closed
https://github.com/metamug/mason/commit/3962ac0dc4d19f9d07ec3ca09a2620cf4c793309
