### ISSUE TITLE
Calling Java Code in jsp

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#34]
How can we execute some logic. Using scriptlets would be a bad idea. What is the preferred mechanism for it ?

**Comment by ancode4** [comment]
You can execute code without assigning its result to output variable. Check the following link:
https://stackoverflow.com/questions/21660068/call-a-java-class-function-without-using-scriptlets-in-jsp/21660185#21660185

**Comment by d3ep4k** [comment]
Why not use the execute tag?

**Comment by ancode4** [comment]
You can use execute tag and assign object returned by your code to an output variable.
