### ISSUE TITLE
Insert/Update bulk records in request.

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#44]
Is there a way to insert/update multiple records in the database by sending JSON in the request?

**Comment by d3ep4k** [comment]
Do we need json or even for form input this issue is valid?

**Comment by ancode4** [comment]
We need this for form params as well.

**Comment by ancode4** [comment]
In case of form params the variables can be sent using array notations.
Eg: userid[]=1&userid[]=15&userid[]=17

**Comment by d3ep4k** [comment]
I think this requires #121 to get an object array to loop. Relying on form data to send array isn't much scalable.

**Comment by richard937** [comment]
bulk request working
![res-req](https://user-images.githubusercontent.com/42942897/84514939-6fb96580-ace9-11ea-896e-3fc48b1b8926.PNG)
