### ISSUE TITLE
Create transform tag

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#58]
Eg:

```xml
<m:transform var="foo" transformer="com.example.Transformer" value="${object}" />
```

The transformer class will contain the code which will process the given value (the value can be a POJO, json etc.) and assign the transformed value to the given variable name.

**Comment by d3ep4k** [comment]
This will also require to add another listener in https://github.com/metamug/mtg-api

```java
public class XMLTransformer implements Transformer{
    public Object tranform(Object input){
        //@TODO code here.
    }
}
```

**Comment by ancode4** [comment]
Not necessary now. You can just use <m:execute> along with <m:arg> https://github.com/metamug/mason/issues/52

**Comment by d3ep4k** [comment]
https://github.com/metamug/mason/issues/52
