### ISSUE TITLE
Not an ISO 8859-1 character

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#63]
![image](https://user-images.githubusercontent.com/1576632/59670816-2cadda80-91da-11e9-8173-a0593ccb3632.png)

**Comment by kaisteel** [comment]
I remember getting this issue while Nadav was using it too
This will fix it, will add it once reached home ```response.getOutputStream().write("output".getBytes("UTF-8"));```

**Comment by d3ep4k** [comment]
@ancode4  has this been fixed? Please close if yes.

**Comment by ancode4** [comment]
Fixed in https://github.com/metamug/mason/commit/552a52aa93fab3953721d90771d0c0d8fae4eca9
