### ISSUE TITLE
Item request 405

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#67]
if the user tries to access the url

```
localhost:8080/backend/v1.0/resource/
```

when there is **no collection request, but there is an item request**, the system throws 405 instead of 404.

**Comment by d3ep4k** [comment]
Shouldn't this say id attribute cannot be null and it should be 412.

```
localhost:8080/backend/v1.0/resource/{id}
```

Since `id` was expected in the request as path param.

**Comment by ancode4** [comment]
The 405 response is returned when <m:resource> reaches its end tag.

There needs to be a check during every collection request, if there is an item request for that resource and no collection request, then throw 412.
