### ISSUE TITLE
Handle InputStream object returned by processable classes.

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#75]
Same manner as done in
https://github.com/metamug/mason/commit/253dec3ccf286651cedad4d32ddf2896cec64ea3

**Comment by d3ep4k** [comment]
Currently execute tag is handling File object.

**Comment by d3ep4k** [comment]
Lets say the we get an InputStream object from our code. Converting `Inputstream` to `File` object requires reading the entire stream into file as follows.

```java
try (FileOutputStream outputStream = new FileOutputStream(file)) {

            int read;
            byte[] bytes = new byte[1024];

            while ((read = inputStream.read(bytes)) != -1) {
                outputStream.write(bytes, 0, read);
            }
        }
```
This loads all the data from the inputstream into memory. This isn't desired for a large file. The stream should be directly written to servlets output.

**Comment by d3ep4k** [comment]
Need some mechanism to get the file name along with inputstream.
