### ISSUE TITLE
Why need <m:upload> for file uploading?

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#86]
@kaisteel 
Mason can always listen to upload event. Why does it need <m:upload> for listening?

**Comment by kaisteel** [comment]
You can say it's like an annotation. `<m:upload>` has logic to call your uploadListener. If you remove that tag then your upload listener event won't be triggered even if your actual file is getting uploaded.

**Comment by ancode4** [comment]
@kaisteel Agree with what you say. However, if we internalise the logic inside the upload tag handler, there won't be a need to print <m:upload> right?

**Comment by d3ep4k** [comment]
No @kaisteel is right.  Your understanding is incorrect. The event handler gets called after successful file upload, which is done by `<m:upload>` tag.  This tag is only added to `<m:request method="post">` tag. 

So the solution is to move the logic into request tag conditionally with method POST.

**Comment by d3ep4k** [comment]
It is out of the TLD as well.  Can we close it now?

https://github.com/metamug/mason/blob/master/src/main/resources/META-INF/mtg-mason.tld
