### ISSUE TITLE
JSON passed in form body is flattened

### ISSUE THREAD

**Issue by S-Mann** [metamug/mason#9]
When I try to pass the JSON in form body, the JSON is flattened. Can't use the flattened JSON in SQL nor Code Execution.

eg- form-body 

```
{"foo":{"bar":123}}
```
is then converted to

```
{"foo.bar":123}
```

**Comment by kaisteel** [comment]
You can use the raw json content using parameter `mtgRawJson`.
So in case you want to use the raw json content inside the resource file you can use `$mtgRawJson`, whereas in code execution you can do `request.getParameter("mtgRawJson")` to get json content.
