### ISSUE TITLE
Integrate Mason into existing webapp.

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#94]

**Comment by kaisteel** [comment]
As long as you maintain a unique URL pattern for Mason's Router filter and necessary folder structure integrating Mason with existing web app shouldn't be a problem.
Ex. Let's say you have got a web app (**foodiez**)with API's to take food orders

- `/foodiez/order` (POST/GET)
- `/foodiez/order/{id}` (PUT/GET/DELETE)

Now you want to integrate Mason using which you've made analytics API. So, create a separate URL pattern for it let's say (/analytics)
Now your mason related calls will be
- `/foodiez/analytics/{order_type}` (With any HTTP Verb)

**Comment by kaisteel** [comment]
Refer [rest-webapp-example](https://github.com/metamug/rest-webapp-example)
